# https://docs.travis-ci.com/user/languages/go/
# https://github.com/codecov/example-go

language: go

go:
  - "1.10"

before_install:
  - go get -t -v ./...
  - go get -u -v golang.org/x/lint/golint

script:
  # https://docs.travis-ci.com/user/customizing-the-build/#implementing-complex-build-steps
  - set -ev
  #
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - golint ./...
  - scripts/gofmt.sh
  - scripts/cross_build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
